export const SIGNAL_EMMITER_CONST = {
    REFRESH_EQUIPMENTS_DATA: 'REFRESH_EQUIPMENTS_DATA',
    REFRESH_EQUIPMENT_MODELS_DATA: "REFRESH_EQUIPMENT_MODELS_DATA",
    REFRESH_EQUIPMENT_TYPES_DATA: "REFRESH_EQUIPMENT_TYPES_DATA",

    REFRESH_LOCATION_DATA: "REFRESH_LOCATION_DATA",

    REFRESH_WHEEL_SCHEMA_DATA: "REFRESH_WHEEL_SCHEMA_DATA",
    REFRESH_WHEEL_SCHEMA_POSITION_DATA: "REFRESH_WHEEL_SCHEMA_POSITION_DATA",

    REFRESH_BUILDING_TYPE_DATA: "REFRESH_BUILDING_TYPE_DATA",
    REFRESH_BUILDING_DATA: "REFRESH_BUILDING_DATA",


    REFRESH_TIRE_BRAND: "REFRESH_TIRE_BRAND",
    REFRESH_TIRE_SIZE: "REFRESH_TIRE_SIZE",
    REFRESH_TIRE_SEASONALITY_TYPE: "REFRESH_TIRE_SEASONALITY_TYPE",
    REFRASH_TIRE_CARCAS_TYPE: "REFRASH_TIRE_CARCAS_TYPE",
    REFRESH_TIRE_MODEL: "REFRESH_TIRE_MODEL",
    REFRESH_TIRE: "REFRESH_TIRE",

    REFRESH_DASHBOARD_DATA: "REFRESH_DASHBOARD_DATA",
    MOVE_TIRE: "MOVE_TIRE"
} as const;